---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medium-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medium-app
  template:
    metadata:
      labels:
        app: medium-app
    spec:
      containers:
      - name: app
        image: nginx:latest
        securityContext:
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: medium-app
