---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: safe-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safe-app
  template:
    metadata:
      labels:
        app: safe-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: app
        image: nginx:1.21.6
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: safe-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: safe-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: safe-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: safe-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: my-app-sa
  namespace: default
roleRef:
  kind: Role
  name: safe-role
  apiGroup: rbac.authorization.k8s.io
